### ISSUE TITLE
5.23.3 version tag missing

### ISSUE THREAD

**Issue by isolovey** [dcm4che/dcm4chee-arc-lang#55]
Causes compilation of `dcm4chee-arc-light` version `5.23.3` to fail:

    Could not find artifact org.dcm4che.dcm4chee-arc:dcm4chee-arc-lang:war:5.23.3 in www.dcm4che.org (http://maven.dcm4che.org)

**Comment by gunterze** [comment]
deployed https://www.dcm4che.org/maven2/org/dcm4che/dcm4chee-arc/dcm4chee-arc-lang/5.23.3/
