### ISSUE TITLE
Fix corrupted zh.json file

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-lang#69]
Initial version of [zh.json](https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json) file contains values not properly enclosed in double quotes. See for eg. 
- https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json#L502
- https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json#L663
- https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json#L684
- https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json#L691
- https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json#L736
- https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json#L1177
- https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json#L1279
- https://github.com/dcm4che/dcm4chee-arc-lang/blob/84ea928c61ff3e683a63d36ea1dd0150360664df/src/main/webapp/assets/locale/zh.json#L1296

Please first pull the latest [zh.json](https://github.com/dcm4che/dcm4chee-arc-lang/blob/master/src/main/webapp/assets/locale/zh.json) file and then rectify values specified above.

**Comment by fanxting** [comment]
fixed
