### ISSUE TITLE
Strangely there couldn't find dcm4chee-arc-lang 5.31.1 Anyone could help? I only saw 5.31.0 out there...

### ISSUE THREAD

**Issue by leon1227** [dcm4che/dcm4chee-arc-lang#87]

**Comment by gunterze** [comment]
Pushed missing dcm4chee-arc-lang 5.31.0, 5.31.1, 5.31.2 to Maven Repository https://www.dcm4che.org/maven2/org/dcm4che/dcm4chee-arc/dcm4chee-arc-lang/
